name: baseline+smart_init
model: facebook/bart-large
#model: facebook/bart-base

# <--------------
# Linearizations
# Comment DFS and uncomment the relevant block if you want to use a different linearization scheme

# DFS
penman_linearization: True
use_pointer_tokens: True
raw_graph: False

# BFS
# penman_linearization: False
# use_pointer_tokens: True
# raw_graph: False

# PENMAN
# penman_linearization: True
# use_pointer_tokens: False
# raw_graph: False

# BART baseline
# penman_linearization: True
# use_pointer_tokens: False
# raw_graph: True

remove_wiki: False
dereify: False
collapse_name_ops: False

# Hparams
batch_size: 500
beam_size: 1
dropout: 0.25
attention_dropout: 0.0
smart_init: True
accum_steps: 10
warmup_steps: 1000
training_steps: 250000
weight_decay: 0.004
grad_norm: 2.5
scheduler: cosine
learning_rate: 0.00005
max_epochs: 30
save_checkpoints: True
log_wandb: False
warm_start: True
use_recategorization: False
best_loss: False
remove_longer_than: 512




#---------------Min---------
#train_constituent: data/AMR/min/train_min_tree.pickle
#dev_constituent: data/AMR/min/train_min_tree.pickle
#test_constituent: data/AMR/min/train_min_tree.pickle
#
#train_sentence: data/AMR/min/train_min_sentence_split.txt
##train_sentence: data/AMR/min/train_min_split_sample.txt
#dev_sentence: data/AMR/min/train_min_sentence_split.txt
#test_sentence: data/AMR/min/train_min_sentence_split.txt
#
#test: data/AMR/min/test.txt
#train: data/AMR/min/train_min.txt
#dev: data/AMR/min/train_min.txt
#
#train_clause: data/AMR/clause/train_min_clause_all.txt
#dev_clause: data/AMR/clause/train_min_clause_all.txt
#test_clause: data/AMR/clause/train_min_clause_all.txt


#-------------AMR2.0-------
train: data/AMR/amr_2.0/train.txt
dev: data/AMR/amr_2.0/dev.txt
test: data/AMR/amr_2.0/test.txt

train_sentence: data/AMR/amr_2.0/sentences/train_sentences_split.txt
dev_sentence: data/AMR/amr_2.0/sentences/dev_sentences_split.txt
test_sentence: data/AMR/amr_2.0/sentences/test_sentences_split.txt

train_constituent: data/AMR/amr_2.0/phrases/train_sentences_tree.pickle
dev_constituent: data/AMR/amr_2.0/phrases/dev_sentences_tree.pickle
test_constituent: data/AMR/amr_2.0/phrases/test_sentences_tree.pickle

train_clause: data/AMR/amr_2.0/clauses/AMR2.0_train_clause_all.txt
dev_clause: data/AMR/amr_2.0/clauses/AMR2.0_dev_clause_all.txt
test_clause: data/AMR/amr_2.0/clauses/AMR2.0_test_clause_all.txt

#=======seed============
seed: 0821
#=======IC===========
IC_steps: 500
IS_IC_Train: False
#======MG=======
head_list: 1-1-2-2-10
mg_list: 1-1-1-1-1
p_mg: 2-3-4
mg_layer_begin_index: 0
mg_layer_end_index: 2
#======Hie=======
hie_layer_begin_index: 0
hie_layer_end_index: 2
hie_mode: 1
#======LSTM=====
lstm_state: 2
